---
title: "Lead Inquiry"
format: html
editor: visual
---
```{r}
library(tidyverse)
library(janitor)

stl_lead <- read_csv(here::here("data", "stl_blood_lead.csv"))

names(stl_lead)

stl_lead <- stl_lead %>% janitor::clean_names()
names(stl_lead)

skimr::skim(stl_lead)
dim(stl_lead)

```
```{r}
names(stl_lead)
stl_lead_prop <- stl_lead |> dplyr::mutate(prop_white = (white/total_pop)*100)
```

```{r}
stl_lead_plot <- ggplot(data = stl_lead_prop, aes(x = prop_white, y = pct_elevated, color = poverty_tot_moe)) +
  geom_point() +
  theme_minimal() +
  labs(title = "Elevated Blood Lead Levels by Population Racial Identity Makeup", x = "Proportion of Population that Identifies as White (%)", y = "Proportion of Population with Elevated Lead Levels in Blood (%)")
print(stl_lead_plot)
ggsave(here::here("figs", "stl_lead_plot.png"), height = 5, width = 6)
```

```{r}
lead_hist <- ggplot(data = stl_lead_prop, aes(x=pct_elevated)) +
  geom_histogram(fill = "red") +
  theme_minimal()

ggsave(here::here("figs", "lead_hist.jpg"), width = 5, height = 6)
print(lead_hist)
```

